
name: Manual deploy preview to Firebase Hosting
on:
  workflow_dispatch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cp firebase-preview.json firebase.json
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOUNDTILE_147DA }}
          channelId: live
          projectId: soundtile-147da
          target: preview
          entryPoint: 'firebase/preview'
